# syntax=docker.io/docker/dockerfile:1.4
ARG _DEV_CONTAINERS_BASE_IMAGE=placeholder


FROM $_DEV_CONTAINERS_BASE_IMAGE AS dev_containers_target_stage

USER root

COPY ./.devpod-internal/ /tmp/build-features/
RUN chmod -R 0755 /tmp/build-features && ls /tmp/build-features

RUN \
echo "_CONTAINER_USER_HOME=$(getent passwd codespace | cut -d: -f6)" >> /tmp/build-features/devcontainer-features.builtin.env && \
echo "_REMOTE_USER_HOME=$(getent passwd codespace | cut -d: -f6)" >> /tmp/build-features/devcontainer-features.builtin.env


RUN cd /tmp/build-features/0 \
&& chmod +x ./devcontainer-features-install.sh \
&& ./devcontainer-features-install.sh


RUN cd /tmp/build-features/1 \
&& chmod +x ./devcontainer-features-install.sh \
&& ./devcontainer-features-install.sh

ENV DOTNET_USE_POLLING_FILE_WATCHER=true
ENV DOTNET_ROOT=/usr/share/dotnet
ENV PATH=$PATH:$DOTNET_ROOT:~/.dotnet/tools
ENV DOTNET_RUNNING_IN_CONTAINER=true
RUN cd /tmp/build-features/2 \
&& chmod +x ./devcontainer-features-install.sh \
&& ./devcontainer-features-install.sh

ENV PATH=/usr/local/sdkman/bin:/usr/local/sdkman/candidates/java/current/bin:/usr/local/sdkman/candidates/gradle/current/bin:/usr/local/sdkman/candidates/maven/current/bin:/usr/local/sdkman/candidates/ant/current/bin:${PATH}
ENV SDKMAN_DIR=/usr/local/sdkman
ENV JAVA_HOME=/usr/local/sdkman/candidates/java/current
RUN cd /tmp/build-features/3 \
&& chmod +x ./devcontainer-features-install.sh \
&& ./devcontainer-features-install.sh


RUN cd /tmp/build-features/4 \
&& chmod +x ./devcontainer-features-install.sh \
&& ./devcontainer-features-install.sh

ENV PATH=/usr/local/php/current/bin:${PATH}
ENV PHP_PATH=/usr/local/php/current
RUN cd /tmp/build-features/5 \
&& chmod +x ./devcontainer-features-install.sh \
&& ./devcontainer-features-install.sh

ENV CARGO_HOME=/usr/local/cargo
ENV RUSTUP_HOME=/usr/local/rustup
ENV PATH=/usr/local/cargo/bin:${PATH}
RUN cd /tmp/build-features/6 \
&& chmod +x ./devcontainer-features-install.sh \
&& ./devcontainer-features-install.sh

ENV NVM_SYMLINK_CURRENT=true
ENV PATH=/usr/local/share/nvm/current/bin:${PATH}
ENV NVM_DIR=/usr/local/share/nvm
RUN cd /tmp/build-features/7 \
&& chmod +x ./devcontainer-features-install.sh \
&& ./devcontainer-features-install.sh

ENV PYTHON_PATH=/usr/local/python/current
ENV PIPX_HOME=/usr/local/py-utils
ENV PIPX_BIN_DIR=/usr/local/py-utils/bin
ENV PATH=/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/jupyter:${PATH}
RUN cd /tmp/build-features/8 \
&& chmod +x ./devcontainer-features-install.sh \
&& ./devcontainer-features-install.sh

ENV DOCKER_BUILDKIT=1
RUN cd /tmp/build-features/9 \
&& chmod +x ./devcontainer-features-install.sh \
&& ./devcontainer-features-install.sh


RUN cd /tmp/build-features/10 \
&& chmod +x ./devcontainer-features-install.sh \
&& ./devcontainer-features-install.sh


RUN cd /tmp/build-features/11 \
&& chmod +x ./devcontainer-features-install.sh \
&& ./devcontainer-features-install.sh

ENV GOROOT=/usr/local/go
ENV GOPATH=/go
ENV PATH=/usr/local/go/bin:/go/bin:${PATH}
RUN cd /tmp/build-features/12 \
&& chmod +x ./devcontainer-features-install.sh \
&& ./devcontainer-features-install.sh



ARG _DEV_CONTAINERS_IMAGE_USER=root
USER $_DEV_CONTAINERS_IMAGE_USER